version: '3'

services:

    db:
        image: 'postgres:13'
        container_name: 'cats_api_db'
        ports:
            - 15432:5432
        environment:
            - 'POSTGRES_DB=cats_db'
            - 'POSTGRES_USER=admin'
            - 'POSTGRES_PASSWORD=pswd123'
