apiVersion: apps/v1
kind: Deployment
metadata:
    name: cats-api-deployment # название деплоймента
    labels:
        app: cats-api # метка
spec:
    #    replicas: 3 # запустить в таком количестве экземпляров те приложения, которые имеют указанную метку
    replicas: 10
    selector:
        matchLabels:
            app: cats-api # по какой метке матчить
    template: # в блоке template описываются параметры запуска нашего приложения
        metadata:
            labels:
                app: cats-api # с какой меткой запустить наше приложение
        spec:
            containers:
                -   name: cats-api-container
                    image: alexz2/cats-api:1.0.0
                    ports:
                        -   containerPort: 8081
                    env:
                        -   name: DATASOURCE_HOST
                            value: 192.168.1.35
                        -   name: spring.mvc.servlet.path
                            value: /cats-api
